name: Trigger auto deployment for hello-java-source

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ java-17 ]
    paths:
    - '**'
    - '.github/workflows/hello-java-source-AutoDeployTrigger-17b403f4-4a9e-4d96-bc54-92089b5691a7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.HELLOJAVASOURCE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HELLOJAVASOURCE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HELLOJAVASOURCE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.HELLOJAVASOURCE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HELLOJAVASOURCE_REGISTRY_PASSWORD }}
          containerAppName: hello-java-source
          resourceGroup: reisz-dev1-tc5
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


